- name: Получение список IP из группы db
  set_fact:
    db_ips: "{{ groups['db'] }}"

- name: Установка haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Установка конфигурацию HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Перезапуск HAProxy
