- name: Полное удаление nginx
  hosts: front
  become: yes
  tasks:

  - name: Удаление nginx и всех его компонентов
    apt:
      name: nginx*
      state: absent
      purge: yes
      autoremove: yes
      update_cache: yes
